### ISSUE TITLE
Possible to run the script locally against a workflow yaml file?

### ISSUE THREAD

**Issue by hanabi1224** [saadmk11/github-actions-version-updater#16]
So that I can do manual upgrades, thanks!

**Comment by saadmk11** [comment]
This option is not available currently :(

But now this action can run without creating a Pull Request and it outputs the `diff` of the changes to the [workflow build summary](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/) Which you can use to manually update your workflow files.

(PR: https://github.com/saadmk11/github-actions-version-updater/pull/18)

**Comment by hanabi1224** [comment]
thanks
