### ISSUE TITLE
Allow actions to be stored inside a sub-directory of a repository

### ISSUE THREAD

**Issue by tobiastom** [saadmk11/github-actions-version-updater#41]
Some action developers seem to put multiple actions into separate directories inside one repository: [Example: flatpak-github-actions](https://github.com/flatpak/flatpak-github-actions).

As this works with GitHub Actions, it would be nice to also be able to get update notifications for them.

**Comment by saadmk11** [comment]
Interesting I have not come across GitHub actions like this. We should support this, I'll try to add this in the next release. PR's are welcome as well :)
