### ISSUE TITLE
dependabot supports github actions

### ISSUE THREAD

**Issue by FabianFrank** [saadmk11/github-actions-version-updater#62]
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot 

might be worth mentioning in the readme?

**Comment by saadmk11** [comment]
Yes you are correct. We should add this on the documentation as an alternative.

**Comment by michen00** [comment]
I can see that the [README documents dependabot as an alternative](https://github.com/crate-ci/typos) for keeping GHA updated. I am curious: what does this Action do that dependabot won't? The relative advantages or disadvantages are not well documented.
