### ISSUE TITLE
Does not run when scheduled?

### ISSUE THREAD

**Issue by SebastianStehle** [saadmk11/github-actions-version-updater#79]
Hi,

do you have an idea why the updater does not run when scheduled: 
https://github.com/Squidex/squidex/actions/workflows/check-updates.yml

Seems that only manual runs actually work.

**Comment by saadmk11** [comment]
> The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.

Reference:
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#scheduled-events
- https://github.com/orgs/community/discussions/27130

There is a chance that the scheduled jobs may also be dropped if the load is high. I just tested this in one of my repositories. The first time it did not run the action at all and the second time it ran the action 5 minutes after the scheduled time.

**Comment by saadmk11** [comment]
I am closing this issue as this is not directly related to this GitHub Action. :)
