### ISSUE TITLE
Action seems to fail when unable to update previously removed workflows

### ISSUE THREAD

**Issue by Zeitsperre** [saadmk11/github-actions-version-updater#81]
For context:

![image](https://github.com/saadmk11/github-actions-version-updater/assets/10819524/1ff7ed4a-e202-44b0-941c-df958f04a7f7)

I'm not sure why the action appears to be failing, but the highest logging reported are the warnings for workflows that have been removed from the master branch. Am I missing a particular configuration?

**Comment by saadmk11** [comment]
I think one or more GitHub actions in your workflow is not using SemVer that's why the action is failing. It would be really helpful if you find such example in your workflow and share it here. I will try to make some changes so that this only displays warnings rather than crashing.

**Comment by saadmk11** [comment]
This action uses GitHub's API to fetch the workflow file paths in a repository and sometimes GitHub's API returns the removed file paths as well. That's why you will see these warnings sometimes.

**Comment by Zeitsperre** [comment]
@saadmk11 Thanks for looking into this.

I imagine that it might be this particular Action: https://github.com/pypa/gh-action-pypi-publish (`pypa/gh-action-pypi-publish@release/v1`). The rest of my integrated Actions seem to follow semantic versioning.

For reference, the failing build can be found here: https://github.com/Ouranosinc/xclim/actions/runs/5728057820

**Comment by saadmk11** [comment]
Similar Issue https://github.com/saadmk11/github-actions-version-updater/issues/76
