### ISSUE TITLE
Appending minor/patch when already added

### ISSUE THREAD

**Issue by baconcheese113** [saadmk11/github-actions-version-updater#88]
It looks like v.0.8.0 is now appending on minor/patch versions for upgrades? First, I'm not sure if that's intended behavior, but if so it's also appending minor/patch to versions which already list them. You can see an example [here](https://github.com/baconcheese113/handle-it-app/pull/28/files#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3)

**Comment by saadmk11** [comment]
Version https://github.com/saadmk11/github-actions-version-updater/releases/tag/v0.8.1 should fix the issue, feel free to reopen if the issue is not fixed.
