### ISSUE TITLE
Not updating to new versions

### ISSUE THREAD

**Issue by baconcheese113** [saadmk11/github-actions-version-updater#94]
Please see [this PR](https://github.com/baconcheese113/handle-it-server/pull/8)

It lists 2 actions that have new versions but does not include the version bump in the PR code changes

The 2 actions are
```
google-github-actions/auth@v0
google-github-actions/deploy-cloudrun@v0
```
And they should have been set to
```
google-github-actions/auth@1.1.1
google-github-actions/deploy-cloudrun@v1.0.2
```

**Comment by kenz** [comment]
@baconcheese113 
You need to remove the quotes from the Uses.
Before:
```yaml
uses: "google-github-actions/auth@v1.1.1"
```

After:
```yaml
uses: google-github-actions/auth@v1.1.1
```

**Comment by saadmk11** [comment]
fixed in https://github.com/saadmk11/github-actions-version-updater/pull/106
